### ISSUE TITLE
Can not catch the data key.

### ISSUE THREAD

**Issue by Light-V** [Asassong/nahida#1]
For most of the time, I can only catch the id key, but the data key is missed. Is there any idea about this issue?

**Comment by Asassong** [comment]
1.Make sure you're on a good Internet connection and there aren't many other extraneous applications.
2.If the above method still does not work，use the file Iridium-py30.py in the fork sniff_raw_data to sniff, find the line startswiths "WindSeedClientNotify" and send it to me.
3.Maybe I should reuse the pcapy, I don't know what I have done, and the pcapy doesn't work on my computer suddenly，so I use scapy instead.
